services:
  oracle-db:
    image: gvenzl/oracle-xe:latest
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: ${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -S system/$${ORACLE_PWD}@localhost:1521/XEPDB1 > /dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 360s
  app:
    build: .
    container_name: java-app
    restart: unless-stopped
    depends_on:
      oracle-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  oracle-data: