create sequence sq_consulta start with 1 increment by 1;
create sequence sq_diagnostico start with 1 increment by 1;
create sequence sq_exame start with 1 increment by 1;
create sequence sq_leitura_wearable start with 1 increment by 1;
create sequence sq_lembrete start with 1 increment by 1;
create sequence sq_pedido_medico start with 1 increment by 1;
create sequence sq_pet start with 1 increment by 1;
create sequence sq_responsavel start with 1 increment by 1;
create sequence sq_responsavel_contato start with 1 increment by 1;
create sequence sq_responsavel_endereco start with 1 increment by 1;
create sequence sq_unidade_veterinario start with 1 increment by 1;
create sequence sq_vacina_tratamento start with 1 increment by 1;
create sequence sq_veterinario start with 1 increment by 1;
create table tb_consulta (data_hora timestamp(9) not null, id number(19,0) not null, pet_id number(19,0) not null, unidade_id number(19,0), veterinario_id number(19,0) not null, observacoes varchar2(255 char), status varchar2(255 char) not null check ((status in ('AGENDADA','REALIZADA','CANCELADA'))), tipo varchar2(255 char) not null check ((tipo in ('PRESENCIAL','TELECONSULTA'))), primary key (id));
create table tb_diagnostico (claudicacao number(1,0) not null check ((claudicacao in (0,1))), confianca_predicao binary_double, diarreia number(1,0) not null check ((diarreia in (0,1))), dificuldade_respiratoria number(1,0) not null check ((dificuldade_respiratoria in (0,1))), frequencia_cardiaca number(10,0), lesoes_pele number(1,0) not null check ((lesoes_pele in (0,1))), perda_apetite number(1,0) not null check ((perda_apetite in (0,1))), secrecao_nasal number(1,0) not null check ((secrecao_nasal in (0,1))), secrecao_ocular number(1,0) not null check ((secrecao_ocular in (0,1))), temperatura_corporal binary_double, tosse number(1,0) not null check ((tosse in (0,1))), vomito number(1,0) not null check ((vomito in (0,1))), consulta_id number(19,0) not null, data timestamp(9) not null, id number(19,0) not null, pet_id number(19,0) not null, analise_gen_ai varchar2(2000 char), doenca_predita varchar2(255 char), duracao_sintomas varchar2(255 char), sintoma1 varchar2(255 char), sintoma2 varchar2(255 char), sintoma3 varchar2(255 char), sintoma4 varchar2(255 char), primary key (id));
create table tb_exame (data date not null, consulta_id number(19,0) not null, id number(19,0) not null, pet_id number(19,0) not null, arquivo_resultado varchar2(255 char), resultado varchar2(255 char), tipo varchar2(255 char) not null, primary key (id));
create table tb_leitura_wearable (alerta_gerado number(1,0) not null check ((alerta_gerado in (0,1))), consumo_diario_acumulado binary_double not null, consumo_ml_registrado binary_double not null, meta_diaria_ml binary_double not null, percentual_meta binary_double not null, id number(19,0) not null, pet_id number(19,0) not null, timestamp timestamp(9) not null, descricao_alerta varchar2(255 char), tipo_alerta varchar2(255 char) check ((tipo_alerta in ('BAIXO_CONSUMO','DESIDRATACAO_CRITICA','META_ATINGIDA','CONSUMO_EXCESSIVO'))), primary key (id));
create table tb_lembrete (data_agendada date, created_at timestamp(9), id number(19,0) not null, pet_id number(19,0) not null, referencia_id number(19,0), responsavel_id number(19,0) not null, mensagem varchar2(255 char) not null, referencia_tipo varchar2(255 char), status varchar2(255 char) check ((status in ('PENDENTE','ENVIADO','FALHOU'))), tipo varchar2(255 char) not null check ((tipo in ('VACINA','CONSULTA','EXAME','MEDICAMENTO','HIDRATACAO'))), primary key (id));
create table tb_pedido_medico (data_limite date, consulta_id number(19,0) not null, created_at timestamp(9) not null, id number(19,0) not null, pet_id number(19,0) not null, descricao varchar2(255 char) not null, instrucoes varchar2(255 char), status varchar2(255 char) not null check ((status in ('PENDENTE','CONCLUIDO','CANCELADO'))), tipo varchar2(255 char) not null check ((tipo in ('EXAME','MEDICAMENTO'))), primary key (id));
create table tb_pet (idade number(10,0), peso binary_double, id number(19,0) not null, responsavel_id number(19,0) not null, veterinario_responsavel_id number(19,0), especie varchar2(255 char) not null, genero varchar2(255 char), nome varchar2(255 char) not null, raca varchar2(255 char), primary key (id));
create table tb_responsavel (ativo number(1,0) check ((ativo in (0,1))), created_at timestamp(9), id number(19,0) not null, cpf varchar2(11 char) not null unique, nome varchar2(150 char) not null, email varchar2(255 char) not null unique, senha varchar2(255 char) not null, primary key (id));
create table tb_responsavel_contato (principal number(1,0) check ((principal in (0,1))), id number(19,0) not null, responsavel_id number(19,0) not null, telefone varchar2(255 char) not null, tipo varchar2(255 char) not null, primary key (id));
create table tb_responsavel_endereco (estado varchar2(2 char) not null, principal number(1,0) check ((principal in (0,1))), cep varchar2(8 char) not null, id number(19,0) not null, responsavel_id number(19,0) not null, bairro varchar2(255 char) not null, cidade varchar2(255 char) not null, complemento varchar2(255 char), logradouro varchar2(255 char) not null, numero varchar2(255 char) not null, primary key (id));
create table tb_unidade_veterinario (estado varchar2(2 char), cep varchar2(8 char), id number(19,0) not null, bairro varchar2(255 char), cidade varchar2(255 char), logradouro varchar2(255 char), nome varchar2(255 char) not null, numero varchar2(255 char), primary key (id));
create table tb_vacina_tratamento (data_aplicacao date not null, proxima_dose date, consulta_id number(19,0), id number(19,0) not null, pet_id number(19,0) not null, veterinario_id number(19,0) not null, dose varchar2(255 char), nome varchar2(255 char) not null, observacoes varchar2(255 char), tipo varchar2(255 char) not null check ((tipo in ('VACINA','MEDICAMENTO','PROCEDIMENTO'))), primary key (id));
create table tb_veterinario (ativo number(1,0) not null check ((ativo in (0,1))), id number(19,0) not null, unidade_id number(19,0), crmv varchar2(255 char) not null unique, email varchar2(255 char) not null unique, especialidade varchar2(255 char), nome varchar2(255 char) not null, senha varchar2(255 char) not null, telefone varchar2(255 char), primary key (id));
alter table tb_consulta add constraint FKe7fr3mapp7j92feenkejc1id5 foreign key (pet_id) references tb_pet;
alter table tb_consulta add constraint FK8gxip3m7jq8klor40ceiyf268 foreign key (unidade_id) references tb_unidade_veterinario;
alter table tb_consulta add constraint FKnm5govt32borvd1jnmb2unmdw foreign key (veterinario_id) references tb_veterinario;
alter table tb_diagnostico add constraint FKq4m429i34dkqm9scjvk9nqjjl foreign key (consulta_id) references tb_consulta;
alter table tb_diagnostico add constraint FK4eiqqohfxukptai2tfo3olhn4 foreign key (pet_id) references tb_pet;
alter table tb_exame add constraint FK6wj3s09hy4hqubv1be0m4daso foreign key (consulta_id) references tb_consulta;
alter table tb_exame add constraint FKh981lx48bpjnoh5758efnyoen foreign key (pet_id) references tb_pet;
alter table tb_leitura_wearable add constraint FK3rs1sksy6dyq0aplb03mkl39e foreign key (pet_id) references tb_pet;
alter table tb_lembrete add constraint FKovua5c7v7mfakc62hr1i9cxds foreign key (pet_id) references tb_pet;
alter table tb_lembrete add constraint FKarm25xeucuwcyt3n1hq1tqn62 foreign key (responsavel_id) references tb_responsavel;
alter table tb_pedido_medico add constraint FKqlsqit1s769jyamd17yqf5ctc foreign key (consulta_id) references tb_consulta;
alter table tb_pedido_medico add constraint FK7fl1xwr0wybddmosmx8b8bu8n foreign key (pet_id) references tb_pet;
alter table tb_pet add constraint FKhw6hrwji2464g76x4q7k44bjm foreign key (responsavel_id) references tb_responsavel;
alter table tb_pet add constraint FKd19e5vd62qc31ltik81oabe14 foreign key (veterinario_responsavel_id) references tb_veterinario;
alter table tb_responsavel_contato add constraint FKl4s98nnb1x7tb1eosw70mopi1 foreign key (responsavel_id) references tb_responsavel;
alter table tb_responsavel_endereco add constraint FKkh2c5qpl4phnihotfect1lbex foreign key (responsavel_id) references tb_responsavel;
alter table tb_vacina_tratamento add constraint FKs6sbnauynl3lha0yxwj53sjvi foreign key (consulta_id) references tb_consulta;
alter table tb_vacina_tratamento add constraint FKljtmakpdvqe2x86645l3fstk4 foreign key (pet_id) references tb_pet;
alter table tb_vacina_tratamento add constraint FKbf8lwxqi01hjjdbx1ckeody2p foreign key (veterinario_id) references tb_veterinario;
alter table tb_veterinario add constraint FK9cs72nuj3g7bskcv8paleo273 foreign key (unidade_id) references tb_unidade_veterinario;
